version: 2
enable-beta-ecosystems: true
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    reviewers:
      - fredrikhr
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    reviewers:
      - fredrikhr
