root: true
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelOptions:
    babelrc: false
    configFile: false
    presets: ['@babel/preset-env']
extends:
  - '@thnetii/eslint-config-base'
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: ['modules']
